# Setup
title:              "Bootstrap Expo"
description:        "Beautiful and inspiring uses of Bootstrap"
url:                "https://expo.getbootstrap.com"
future:             false
permalink:          pretty
paginate:           10

source:             src

# Settings
destination:        ./_gh_pages

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
    style:          compressed

# Local Server
host:               localhost # same as default value '127.0.0.1' but reads better

# Links
#expo_repo:          https://github.com/twbs/bootstrap-expo
expo_new_issue:     https://github.com/twbs/bootstrap-expo/issues/new
docs:               https://getbootstrap.com
blog:               https://blog.getbootstrap.com

redirect_from:
  json: false
