# Dependencies
highlighter:      false

# Permalinks
permalink:        pretty

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
    style:        compressed

# Settings
destination:      ./_gh_pages
exclude:
  - .netlify
  - .sass-cache
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
paginate:         10
encoding:         UTF-8
future:           false
name:             Bootstrap Expo
description:      Beautiful and inspiring uses of Bootstrap
url:              https://expo.getbootstrap.com

# Links
expo_repo:        https://github.com/twbs/bootstrap-expo/
expo_new_issue:   https://github.com/twbs/bootstrap-expo/issues/new

docs:             https://getbootstrap.com
blog:             https://blog.getbootstrap.com
